preload = /home/frathol/Pictures/Wallpaper/current_wallpaper.png
# wallpaper = eDP-1,/home/frathol/Pictures/Wallpaper/current_wallpaper.png
wallpaper = ,/home/frathol/Pictures/Wallpaper/current_wallpaper.png
splash = false
